---
title: "Next Word Predictor"
author: "Nicholas Neo"
date: "21 July 2020"
output:
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Aim of this Next Word Predictor

- The goal of this project is to build a Natural Language Processing (NLP) model that takes in an input from the user, which can be a word, a phrase or an incomplete sentence.
- The algorithm will then use the inputs given and predict what the **next top matching word** should be based on the model that its being trained on.
- The algorithm will also predict the **next 3 best alternative words** that should come after the input from the user.
- User can start entering an input in the message box and wait for ~3-5 seconds to see its effect!

## Data and Algorithm
#### Data - **Corpora from SwiftKey**
- The dataset consist of text crawled from twitter, blogs and news in 4 languages (US, DE, FI and RU).
- As a starter, we will only build our model with the English dataset.

#### Algorithm - **Katz's back-off Model**
- An n-gram language model that estimates the conditional probabilty of a word given its history in the n-gram.
- In the app's context, we adopted a **quad-gram (4 words) language model** and use it to predict the **last 3 words** that the user have input.
- If there are less than 3 words, then it will based enitrely on what the user have input.

## Brief Project Pipeline
- Web Scraping to create the raw datasets
- Process the raw datasets by cleaning the dataset
- Do exploratory data analysis to get insights from the datasets
- Do ngram analysis and determine which combination of words happen more frequently than the other combinations
- Apply Katz's back-off algorithm to build the model
- Set up the web application using Shiny
- Deploy the application on shinyapps.io

## Try the **Next Word Predictor** now!
#### The App
- [Next Word Predictor](https://thatnicneo.shinyapps.io/next-word-predictor/)

#### Source Code
- [GitHub](https://github.com/nicholasneo78/next-word-predictor)

